esphome:
  name: loco040de532

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xfggjdfhj"

ota:
  - platform: esphome
    password: "xfggjdfhj"

wifi:
  ssid: "sqfgsdgh"
  password: "sdfhdsgjsfhgj"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Loco040De532 Fallback Hotspot"
    password: "f9TQeX8LgmIu"

captive_portal:
    